# Generated by Django 4.1.6 on 2023-02-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_customer_email_booking_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_tickets',
        ),
    ]
