# Generated by Django 4.1.6 on 2023-02-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_booking_number_of_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='eventname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
