# Generated by Django 4.1.6 on 2023-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_screenshot',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
